In [1]:
#Dependencies
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv(r"train.csv") #You need to change #directory accordingly
dataset.head(10) #Return 10 rows of data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   
8        174        7  ...        386       836  1099    17     1         20   
9         93        5  ...       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  
8        1             0     0            0  
9        1             0     0            0  

[10 rows x 21 columns]

In [17]:
#Changing pandas dataframe to numpy array
X = dataset.iloc[:,:20].values
y = dataset.iloc[:,20:21].values
print(X)
print(y)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 1.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]
[[1]
 [2]
 [2]
 ...
 [3]
 [0]
 [3]]


In [3]:
#Normalizing the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [4]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [7]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense
# Neural network
model = Sequential()
model.add(Dense(16, input_dim=20, activation="relu"))
model.add(Dense(12, activation="relu"))
model.add(Dense(4, activation="softmax"))

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
history = model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
29/29 [==============================] - 1s 3ms/step - loss: 1.4156 - accuracy: 0.2878
Epoch 2/100
29/29 [==============================] - 0s 2ms/step - loss: 1.3607 - accuracy: 0.3283
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 1.3167 - accuracy: 0.3628
Epoch 4/100
29/29 [==============================] - 0s 3ms/step - loss: 1.2712 - accuracy: 0.4067
Epoch 5/100
29/29 [==============================] - 0s 3ms/step - loss: 1.2149 - accuracy: 0.4517
Epoch 6/100
29/29 [==============================] - 0s 3ms/step - loss: 1.1451 - accuracy: 0.5011
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 1.0632 - accuracy: 0.5356
Epoch 8/100
29/29 [==============================] - 0s 3ms/step - loss: 0.9742 - accuracy: 0.5844
Epoch 9/100
29/29 [==============================] - 0s 2ms/step - loss: 0.8867 - accuracy: 0.6261
Epoch 10/100
29/29 [==============================] - 0s 2ms/step - loss: 0.8046 - accuracy: 0.6711
Epoch 11/

In [10]:
y_pred = model.predict(X_test)
#Converting predictions to label
pred = list()
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))
#Converting one hot encoded test label to label
test = list()
for i in range(len(y_test)):
    test.append(np.argmax(y_test[i]))

7/7 [==============================] - 0s 3ms/step


In [11]:
from sklearn.metrics import accuracy_score
a = accuracy_score(pred,test)
print('Accuracy is:', a*100)

Accuracy is: 86.0


In [34]:
print(X_test[0])

[-0.68862454  1.0100505   0.95335845 -1.01918398  0.15908825  0.95788598
  1.37551707 -1.04649512 -0.31785093 -1.10197128 -0.64598879  0.02680371
 -0.72557684 -0.0693552  -0.07276497  0.51270767 -1.10039396  0.55964063
  0.99401789 -1.01409939]
